=== gorky/jSCSI/bundles/target/src/main/resources/jscsi-target.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://www.jscsi.org/2010-04"
	xmlns="http://www.jscsi.org/2010-04" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="TargetNameType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100" />
			<xs:pattern
				value="iqn\.[0-9]{4}-[0-9]{2}\.([a-z0-9\-])+(\.([a-z0-9\-])+)*\:([a-z0-9\-])+(\.([a-z0-9\-])+)*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TargetPortType">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="65536" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="FileDeviceType">
		<xs:sequence>
			<!-- Storage where the data of the target should be stored to. -->
			<xs:element name="FilePath" type="xs:string" default="storage.dat"
				minOccurs="1" maxOccurs="1" />
			<!-- If storage is fresh, define the file size for creation process in GB. -->
			<xs:element name="FileLength" type="xs:double" default="0.5"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>


	<xs:element name="configuration">
		<xs:complexType>
			<xs:all>
				<xs:element name="TargetName" type="TargetNameType"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="TargetAlias" type="xs:string"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="Port" type="TargetPortType" default="3260"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="StorageFile" type="FileDeviceType"
					maxOccurs="1" />
				<xs:element name="AllowSloppyNegotiation" type="xs:boolean"
					default="false" minOccurs="0" maxOccurs="1" />
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gorky/jSCSI/bundles/target/src/main/resources/jscsi-target.xml
<?xml version="1.0" encoding="UTF-8" ?>

<configuration xmlns="http://www.jscsi.org/2010-04"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jscsi.org/2010-04 jscsi-target.xsd">
	
	<TargetName>iqn.2010-04.local-test:disk-1</TargetName>
	<TargetAlias>jSCSI Target</TargetAlias>
	<Port>3260</Port>
	<StorageFile>
		<FilePath>storage.dat</FilePath>
		 <FileLength>0.75</FileLength>
	</StorageFile>
	<AllowSloppyNegotiation>true</AllowSloppyNegotiation>
</configuration>
